import argparse
import getpass
import json
from multiprocessing import process

import jwt
import requests


def parse_args():
    parser = argparse.ArgumentParser(
        prog="token", description="generate and/or decode tokens generated by keycloack"
    )

    parser.add_argument(
        "-u",
        "--username",
        help="authenticate and create a token using this username instead of your username",
    )
    parser.add_argument(
        "-p",
        "--password",
        help="authenticate and create a token using this password (will be prompted if not specified)",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="debug printing")
    parser.add_argument(
        "-d",
        "--decode",
        action="store_true",
        help="decode the given access token and print the information",
    )
    parser.add_argument(
        "-f",
        "--file",
        help="read token from this file if decoding, otherwise save the generated token to this file",
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    def debug_log(message):
        if args.verbose:
            print(message)

    if args.decode:
        debug_log("decoding token..")
        access_token = args.decode
        if args.file:
            with open(args.file, "r") as token_file:
                access_token = token_file.read()

        token_data = jwt.decode(
            access_token,
            options={"verify_signature": False},
        )
        print(json.dumps(token_data))
    else:
        debug_log("generating token..")
        user = getpass.getuser()
        if args.username:
            user = args.username

        debug_log(f"user: {user}")

        password = args.password
        if not password:
            password = getpass.getpass()

        data = {
            "grant_type": "password",
            "client_id": "token_generator",
            "username": user,
            "password": password,
        }

        debug_log(f"request: {data}")

        url = "http://localhost:8080/realms/topics-realm/protocol/openid-connect/token"

        r = requests.post(
            url, data, headers={"Content-Type": "application/x-www-form-urlencoded"}
        )

        debug_log(f"response: {r}")

        result = r.json()

        if "error" in result and result["error"] == "invalid_client":
            print(
                "Invalid client: '",
                data["client_id"],
                "'. Make sure you've created the client 'token_generator' in Keycloak",
            )
        else:
            r.raise_for_status()

            debug_log(f"response body: {json.dumps(result)}")

            access_token = result["access_token"]

            if args.file:
                with open(args.file, "w") as token_file:
                    token_file.write(access_token)
            else:
                print(access_token)
